//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManarAlSabeel.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ManarAlSabeel.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل بيانات الدورة العلمية بنجاح.
        /// </summary>
        public static string EditedSemesterInfoSuccessful {
            get {
                return ResourceManager.GetString("EditedSemesterInfoSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل بيانات ولي الأمر بنجاح.
        /// </summary>
        public static string EditGuardianSuccessful {
            get {
                return ResourceManager.GetString("EditGuardianSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل بيانات الطالب بنجاح.
        /// </summary>
        public static string EditStudentSuccessful {
            get {
                return ResourceManager.GetString("EditStudentSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل بيانات المدرس بنجاح.
        /// </summary>
        public static string EditTeacherSuccessful {
            get {
                return ResourceManager.GetString("EditTeacherSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية انشاء ولي الأمر بنجاح.
        /// </summary>
        public static string GuardianCreatedSuccessfully {
            get {
                return ResourceManager.GetString("GuardianCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف ولي الأمر بنجاح.
        /// </summary>
        public static string GuardianDeletedSuccessfully {
            get {
                return ResourceManager.GetString("GuardianDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك أدخل رقم جوال ولي الأمر.
        /// </summary>
        public static string GuardianMobileNumberIsRequired {
            get {
                return ResourceManager.GetString("GuardianMobileNumberIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك أدخل اسم ولي الأمر.
        /// </summary>
        public static string GuardianNameIsRequired {
            get {
                return ResourceManager.GetString("GuardianNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في اسم المستخدم أو كلمة المرور.
        /// </summary>
        public static string IncorrectLoginData {
            get {
                return ResourceManager.GetString("IncorrectLoginData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية انشاء الدورة العلمية بنجاح.
        /// </summary>
        public static string SemesterCreatedSuccessfully {
            get {
                return ResourceManager.GetString("SemesterCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف الدورة التعليمية بنجاح.
        /// </summary>
        public static string SemesterDeletedSuccessfully {
            get {
                return ResourceManager.GetString("SemesterDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك أدخل تاريخ انتهاء الدورة التعلمية.
        /// </summary>
        public static string SemesterEndDateIsRequired {
            get {
                return ResourceManager.GetString("SemesterEndDateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك أدخل اسم الدورة التعلمية.
        /// </summary>
        public static string SemesterNameIsRequired {
            get {
                return ResourceManager.GetString("SemesterNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك أدخل تاريخ بداية الدورة التعلمية.
        /// </summary>
        public static string SemesterStartDateIsRequired {
            get {
                return ResourceManager.GetString("SemesterStartDateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك أدخل تاريخ ميلاد الطالب.
        /// </summary>
        public static string StudentBirthdayRequired {
            get {
                return ResourceManager.GetString("StudentBirthdayRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية انشاء الطالب بنجاح.
        /// </summary>
        public static string StudentCreatedSuccessfully {
            get {
                return ResourceManager.GetString("StudentCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف الطالب بنجاح.
        /// </summary>
        public static string StudentDeletedSuccessfully {
            get {
                return ResourceManager.GetString("StudentDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك أدخل اسم الطالب.
        /// </summary>
        public static string StudentNameRequired {
            get {
                return ResourceManager.GetString("StudentNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية انشاء المدرس بنجاح.
        /// </summary>
        public static string TeacherCreatedSuccessfully {
            get {
                return ResourceManager.GetString("TeacherCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف المدرس بنجاح.
        /// </summary>
        public static string TeacherDeletedSuccessfully {
            get {
                return ResourceManager.GetString("TeacherDeletedSuccessfully", resourceCulture);
            }
        }
    }
}
