//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManarAlSabeel.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ManarAlSabeel.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم انشاء مقابلة قبول الطالب بنجاح.
        /// </summary>
        public static string AdmissionInterviewCreated {
            get {
                return ResourceManager.GetString("AdmissionInterviewCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل بيانات مقابلة قبول الطالب بنجاح.
        /// </summary>
        public static string AdmissionInterviewUpdated {
            get {
                return ResourceManager.GetString("AdmissionInterviewUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك أدخل مقدار حفظ المدرس.
        /// </summary>
        public static string AmountOfMemorizationIsRequired {
            get {
                return ResourceManager.GetString("AmountOfMemorizationIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم انشاء فصل التدريس بنجاح.
        /// </summary>
        public static string ClassCreatedSuccessfully {
            get {
                return ResourceManager.GetString("ClassCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف فصل التدريس بنجاح.
        /// </summary>
        public static string ClassDeletedSuccessfully {
            get {
                return ResourceManager.GetString("ClassDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك أدخل اسم الفصل الدراسي.
        /// </summary>
        public static string ClassNameIsRequired {
            get {
                return ResourceManager.GetString("ClassNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك اختر الدورة العلمية.
        /// </summary>
        public static string ClassSemesterIsRequired {
            get {
                return ResourceManager.GetString("ClassSemesterIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك اختر مدرس الفصل.
        /// </summary>
        public static string ClassTeacherIsRequired {
            get {
                return ResourceManager.GetString("ClassTeacherIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل بيانات فصل التدريس بنجاح.
        /// </summary>
        public static string EditedClassInfoSuccessful {
            get {
                return ResourceManager.GetString("EditedClassInfoSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل بيانات الدورة العلمية بنجاح.
        /// </summary>
        public static string EditedSemesterInfoSuccessful {
            get {
                return ResourceManager.GetString("EditedSemesterInfoSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل بيانات ولي الأمر بنجاح.
        /// </summary>
        public static string EditGuardianSuccessful {
            get {
                return ResourceManager.GetString("EditGuardianSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل بيانات الطالب بنجاح.
        /// </summary>
        public static string EditStudentSuccessful {
            get {
                return ResourceManager.GetString("EditStudentSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل بيانات المدرس بنجاح.
        /// </summary>
        public static string EditTeacherSuccessful {
            get {
                return ResourceManager.GetString("EditTeacherSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم اضافة بيانات الامتحان بنجاح.
        /// </summary>
        public static string ExamAdded {
            get {
                return ResourceManager.GetString("ExamAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك أدخل ملاحظة الامتحان.
        /// </summary>
        public static string ExamCommentsIsRequired {
            get {
                return ResourceManager.GetString("ExamCommentsIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك أدخل تاريخ الامتحان.
        /// </summary>
        public static string ExamDateIsRequired {
            get {
                return ResourceManager.GetString("ExamDateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل بيانات الامتحان بنجاح.
        /// </summary>
        public static string ExamEditedSuccessfully {
            get {
                return ResourceManager.GetString("ExamEditedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من أفضلك أدخل الوقت المتوقع لانهاء القرآن.
        /// </summary>
        public static string ExpectedTimeToFinishQuraanRequired {
            get {
                return ResourceManager.GetString("ExpectedTimeToFinishQuraanRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية انشاء ولي الأمر بنجاح.
        /// </summary>
        public static string GuardianCreatedSuccessfully {
            get {
                return ResourceManager.GetString("GuardianCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف ولي الأمر بنجاح.
        /// </summary>
        public static string GuardianDeletedSuccessfully {
            get {
                return ResourceManager.GetString("GuardianDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك اختر ولي أمر الطلب.
        /// </summary>
        public static string GuardianIsRequired {
            get {
                return ResourceManager.GetString("GuardianIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك أدخل رقم جوال ولي الأمر.
        /// </summary>
        public static string GuardianMobileNumberIsRequired {
            get {
                return ResourceManager.GetString("GuardianMobileNumberIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك أدخل اسم ولي الأمر.
        /// </summary>
        public static string GuardianNameIsRequired {
            get {
                return ResourceManager.GetString("GuardianNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في اسم المستخدم أو كلمة المرور.
        /// </summary>
        public static string IncorrectLoginData {
            get {
                return ResourceManager.GetString("IncorrectLoginData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك أدخل تاريخ المقابلة.
        /// </summary>
        public static string InterviewDateIsRequired {
            get {
                return ResourceManager.GetString("InterviewDateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك أدخل نتيجة المقابلة.
        /// </summary>
        public static string InterviewResultIsRequired {
            get {
                return ResourceManager.GetString("InterviewResultIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من أفضلك أدخل مقدار حفظ الطالب عند المقابلة.
        /// </summary>
        public static string MemorizationAmountIsRequired {
            get {
                return ResourceManager.GetString("MemorizationAmountIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد فصول دراسة في الدورة الحالية.
        /// </summary>
        public static string NoClassesInCurrentSemester {
            get {
                return ResourceManager.GetString("NoClassesInCurrentSemester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد طلاب بالفصل الدراسي.
        /// </summary>
        public static string NoStudentsInTheClass {
            get {
                return ResourceManager.GetString("NoStudentsInTheClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف تسجيل الطالب بنجاح.
        /// </summary>
        public static string RegisteredStudentDeletedSuccessfully {
            get {
                return ResourceManager.GetString("RegisteredStudentDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية انشاء الدورة العلمية بنجاح.
        /// </summary>
        public static string SemesterCreatedSuccessfully {
            get {
                return ResourceManager.GetString("SemesterCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف الدورة التعليمية بنجاح.
        /// </summary>
        public static string SemesterDeletedSuccessfully {
            get {
                return ResourceManager.GetString("SemesterDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك أدخل تاريخ انتهاء الدورة التعلمية.
        /// </summary>
        public static string SemesterEndDateIsRequired {
            get {
                return ResourceManager.GetString("SemesterEndDateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك أدخل اسم الدورة التعلمية.
        /// </summary>
        public static string SemesterNameIsRequired {
            get {
                return ResourceManager.GetString("SemesterNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك أدخل تاريخ بداية الدورة التعلمية.
        /// </summary>
        public static string SemesterStartDateIsRequired {
            get {
                return ResourceManager.GetString("SemesterStartDateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك أدخل تاريخ ميلاد الطالب.
        /// </summary>
        public static string StudentBirthdayRequired {
            get {
                return ResourceManager.GetString("StudentBirthdayRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية انشاء الطالب بنجاح.
        /// </summary>
        public static string StudentCreatedSuccessfully {
            get {
                return ResourceManager.GetString("StudentCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف الطالب بنجاح.
        /// </summary>
        public static string StudentDeletedSuccessfully {
            get {
                return ResourceManager.GetString("StudentDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك أدخل اسم الطالب.
        /// </summary>
        public static string StudentNameRequired {
            get {
                return ResourceManager.GetString("StudentNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفوا ، تم تسجيل هذا الطالب في هذه الدورة العلمية من قبل.
        /// </summary>
        public static string StudentRegisteredBefore {
            get {
                return ResourceManager.GetString("StudentRegisteredBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تسجيل الطالب بنجاح.
        /// </summary>
        public static string StudentRegisteredSuccesfully {
            get {
                return ResourceManager.GetString("StudentRegisteredSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل بيانات تسجيل الطالب بنجاح.
        /// </summary>
        public static string StudentRegistrationEditedSuccesfully {
            get {
                return ResourceManager.GetString("StudentRegistrationEditedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك أدخل تاريخ ميلاد المدرس.
        /// </summary>
        public static string TeacherBirthdateIsRequired {
            get {
                return ResourceManager.GetString("TeacherBirthdateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك اختر محل ميلاد المدرس.
        /// </summary>
        public static string TeacherBirthPlaceIsRequired {
            get {
                return ResourceManager.GetString("TeacherBirthPlaceIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية انشاء المدرس بنجاح.
        /// </summary>
        public static string TeacherCreatedSuccessfully {
            get {
                return ResourceManager.GetString("TeacherCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف المدرس بنجاح.
        /// </summary>
        public static string TeacherDeletedSuccessfully {
            get {
                return ResourceManager.GetString("TeacherDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك أدخل رقم جوال المدرس.
        /// </summary>
        public static string TeacherMobileNumberIsRequired {
            get {
                return ResourceManager.GetString("TeacherMobileNumberIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك أدخل اسم المدرس.
        /// </summary>
        public static string TeacherNameIsRequired {
            get {
                return ResourceManager.GetString("TeacherNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك اختر الجنسية.
        /// </summary>
        public static string TeacherNationalityIsRequired {
            get {
                return ResourceManager.GetString("TeacherNationalityIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد دورة حالية في الوقت الحالي بالمركز.
        /// </summary>
        public static string ThereIsNoCurrentSemester {
            get {
                return ResourceManager.GetString("ThereIsNoCurrentSemester", resourceCulture);
            }
        }
    }
}
