//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManarAlSabeel.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringTable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ManarAlSabeel.Resources.StringTable", typeof(StringTable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنسية المكتسبة.
        /// </summary>
        public static string AcquiredNationality {
            get {
                return ResourceManager.GetString("AcquiredNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعلان.
        /// </summary>
        public static string Ad {
            get {
                return ResourceManager.GetString("Ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة مقابلة قبول الطالب الآن.
        /// </summary>
        public static string AddAdmissionInterviewNow {
            get {
                return ResourceManager.GetString("AddAdmissionInterviewNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة فصل.
        /// </summary>
        public static string AddClass {
            get {
                return ResourceManager.GetString("AddClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة نشاط تأديبي.
        /// </summary>
        public static string AddDisciplinaryActivity {
            get {
                return ResourceManager.GetString("AddDisciplinaryActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة امتحان.
        /// </summary>
        public static string AddExam {
            get {
                return ResourceManager.GetString("AddExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل طالب جديد بالدورة.
        /// </summary>
        public static string AddRegisteredStudentToSemester {
            get {
                return ResourceManager.GetString("AddRegisteredStudentToSemester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة دورة تعليمية.
        /// </summary>
        public static string AddSemester {
            get {
                return ResourceManager.GetString("AddSemester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة طالب.
        /// </summary>
        public static string AddStudent {
            get {
                return ResourceManager.GetString("AddStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة مقابلة قبول للطالب.
        /// </summary>
        public static string AddStudentAdmissiondInterview {
            get {
                return ResourceManager.GetString("AddStudentAdmissiondInterview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة ولي أمر.
        /// </summary>
        public static string AddStudentGuardian {
            get {
                return ResourceManager.GetString("AddStudentGuardian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة مدرس.
        /// </summary>
        public static string AddTeacher {
            get {
                return ResourceManager.GetString("AddTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ المقابلة.
        /// </summary>
        public static string AdmissionInterviewDate {
            get {
                return ResourceManager.GetString("AdmissionInterviewDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار الحفظ.
        /// </summary>
        public static string AdmissionInterviewMemorizationAmount {
            get {
                return ResourceManager.GetString("AdmissionInterviewMemorizationAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات المقابلة.
        /// </summary>
        public static string AdmissionInterviewNotes {
            get {
                return ResourceManager.GetString("AdmissionInterviewNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحة مقابلة قبول الطالب.
        /// </summary>
        public static string AdmissionInterviewPage {
            get {
                return ResourceManager.GetString("AdmissionInterviewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نتيجة المقابلة.
        /// </summary>
        public static string AdmissionInterviewResult {
            get {
                return ResourceManager.GetString("AdmissionInterviewResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السن.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل أنت متأكد؟.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محل الميلاد.
        /// </summary>
        public static string BirthPlace {
            get {
                return ResourceManager.GetString("BirthPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفرع.
        /// </summary>
        public static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادارة المركز.
        /// </summary>
        public static string CenterAdministration {
            get {
                return ResourceManager.GetString("CenterAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الأبناء.
        /// </summary>
        public static string ChildrenCount {
            get {
                return ResourceManager.GetString("ChildrenCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفصل الدراسي.
        /// </summary>
        public static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فصول التدريس.
        /// </summary>
        public static string Classes {
            get {
                return ResourceManager.GetString("Classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة فصول الدراسة.
        /// </summary>
        public static string ClassesList {
            get {
                return ResourceManager.GetString("ClassesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدورة العلمية الحالية.
        /// </summary>
        public static string CurrentSemester {
            get {
                return ResourceManager.GetString("CurrentSemester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المرحلة الدراسية الحالية.
        /// </summary>
        public static string CurrentStudySatge {
            get {
                return ResourceManager.GetString("CurrentStudySatge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الميلاد.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ التسجيل.
        /// </summary>
        public static string DateOfRegister {
            get {
                return ResourceManager.GetString("DateOfRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حـذف.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف تسجيل الطالب.
        /// </summary>
        public static string DeleteRegisteredStudent {
            get {
                return ResourceManager.GetString("DeleteRegisteredStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأنشطة التأديبية.
        /// </summary>
        public static string DisciplinaryActivities {
            get {
                return ResourceManager.GetString("DisciplinaryActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطلق.
        /// </summary>
        public static string Divorced {
            get {
                return ResourceManager.GetString("Divorced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل بيانات فصل تدريس.
        /// </summary>
        public static string EditClass {
            get {
                return ResourceManager.GetString("EditClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل بيانات الامتحان.
        /// </summary>
        public static string EditExam {
            get {
                return ResourceManager.GetString("EditExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل بيانات امتحان.
        /// </summary>
        public static string EditExamPageTitle {
            get {
                return ResourceManager.GetString("EditExamPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل بيانات طالب مسجل.
        /// </summary>
        public static string EditRegisteredStudent {
            get {
                return ResourceManager.GetString("EditRegisteredStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل بيانات دورة تعليمية.
        /// </summary>
        public static string EditSemester {
            get {
                return ResourceManager.GetString("EditSemester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل بيانات ولي أمر.
        /// </summary>
        public static string EditStudentGuardian {
            get {
                return ResourceManager.GetString("EditStudentGuardian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل بيات الطالب.
        /// </summary>
        public static string EditStudentInfo {
            get {
                return ResourceManager.GetString("EditStudentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل بيانات مدرس.
        /// </summary>
        public static string EditTeacherInfo {
            get {
                return ResourceManager.GetString("EditTeacherInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الانتهاء.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسائي.
        /// </summary>
        public static string Evening {
            get {
                return ResourceManager.GetString("Evening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درجات اضافية.
        /// </summary>
        public static string ExamBonusPoints {
            get {
                return ResourceManager.GetString("ExamBonusPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظة على الامتحان.
        /// </summary>
        public static string ExamComments {
            get {
                return ResourceManager.GetString("ExamComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الامتحان.
        /// </summary>
        public static string ExamDate {
            get {
                return ResourceManager.GetString("ExamDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقدير الامتحان.
        /// </summary>
        public static string ExamGrade {
            get {
                return ResourceManager.GetString("ExamGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الامتحانات.
        /// </summary>
        public static string Exams {
            get {
                return ResourceManager.GetString("Exams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة امتحانات طالب مسجل.
        /// </summary>
        public static string ExamsListPageTitle {
            get {
                return ResourceManager.GetString("ExamsListPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشرف الامتحان.
        /// </summary>
        public static string ExamSupervisor {
            get {
                return ResourceManager.GetString("ExamSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الامتحان.
        /// </summary>
        public static string ExamType {
            get {
                return ResourceManager.GetString("ExamType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفترة المتوقعة لانهاء القرآن.
        /// </summary>
        public static string ExpectedPeriodToFinishQuraan {
            get {
                return ResourceManager.GetString("ExpectedPeriodToFinishQuraan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مفصول.
        /// </summary>
        public static string Expelled {
            get {
                return ResourceManager.GetString("Expelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المشرف الخارجي.
        /// </summary>
        public static string ExternalSupervisor {
            get {
                return ResourceManager.GetString("ExternalSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنثى.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إناث.
        /// </summary>
        public static string Females {
            get {
                return ResourceManager.GetString("Females", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صديق.
        /// </summary>
        public static string Friend {
            get {
                return ResourceManager.GetString("Friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ولي الأمر.
        /// </summary>
        public static string Guardian {
            get {
                return ResourceManager.GetString("Guardian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أولياء الأمـور.
        /// </summary>
        public static string Guardians {
            get {
                return ResourceManager.GetString("Guardians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حنفي.
        /// </summary>
        public static string Hanafy {
            get {
                return ResourceManager.GetString("Hanafy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حنبلي.
        /// </summary>
        public static string Hanbally {
            get {
                return ResourceManager.GetString("Hanbally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان المنزل.
        /// </summary>
        public static string HomeAddress {
            get {
                return ResourceManager.GetString("HomeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هاتف المنزل.
        /// </summary>
        public static string HomePhone {
            get {
                return ResourceManager.GetString("HomePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كيف تعرفت على المركز.
        /// </summary>
        public static string HowDidYouTheCenter {
            get {
                return ResourceManager.GetString("HowDidYouTheCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير فعال.
        /// </summary>
        public static string InActive {
            get {
                return ResourceManager.GetString("InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدورة التعليمية الحالية.
        /// </summary>
        public static string IsCurrentSemetser {
            get {
                return ResourceManager.GetString("IsCurrentSemetser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل هو مسجل بالمواصلات.
        /// </summary>
        public static string IsStudentRegisteredInTransportations {
            get {
                return ResourceManager.GetString("IsStudentRegisteredInTransportations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخر شهادة دراسية.
        /// </summary>
        public static string LastStudyDegree {
            get {
                return ResourceManager.GetString("LastStudyDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دخول.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الدخول.
        /// </summary>
        public static string LoginPageTitle {
            get {
                return ResourceManager.GetString("LoginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذكر.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذكور.
        /// </summary>
        public static string Males {
            get {
                return ResourceManager.GetString("Males", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مالكي.
        /// </summary>
        public static string Malky {
            get {
                return ResourceManager.GetString("Malky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مركز منار السبيل.
        /// </summary>
        public static string ManarAlSabeel {
            get {
                return ResourceManager.GetString("ManarAlSabeel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة الاجتماعية.
        /// </summary>
        public static string MaritalStatus {
            get {
                return ResourceManager.GetString("MaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الزواج.
        /// </summary>
        public static string MarriageDate {
            get {
                return ResourceManager.GetString("MarriageDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متزوج.
        /// </summary>
        public static string Married {
            get {
                return ResourceManager.GetString("Married", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الجوال.
        /// </summary>
        public static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صباحي.
        /// </summary>
        public static string Morning {
            get {
                return ResourceManager.GetString("Morning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنسية.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنسية الأصلية.
        /// </summary>
        public static string OriginalNationality {
            get {
                return ResourceManager.GetString("OriginalNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أخرى.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم هاتف اضافي.
        /// </summary>
        public static string OtherPhoneNumber {
            get {
                return ResourceManager.GetString("OtherPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادارة الأفراد.
        /// </summary>
        public static string PeopleAdministration {
            get {
                return ResourceManager.GetString("PeopleAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار الحفظ من القرآن.
        /// </summary>
        public static string QuraanMemorizationAmount {
            get {
                return ResourceManager.GetString("QuraanMemorizationAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المذهب الديني.
        /// </summary>
        public static string ReligiousIdeology {
            get {
                return ResourceManager.GetString("ReligiousIdeology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الفصل الدراسي.
        /// </summary>
        public static string SchoolClassName {
            get {
                return ResourceManager.GetString("SchoolClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المدرسة.
        /// </summary>
        public static string SchoolName {
            get {
                return ResourceManager.GetString("SchoolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر صورة الطالب.
        /// </summary>
        public static string SelectStudentPhoto {
            get {
                return ResourceManager.GetString("SelectStudentPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدورة التعليمية.
        /// </summary>
        public static string Semester {
            get {
                return ResourceManager.GetString("Semester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة الطلاب المسجلين بالدورة.
        /// </summary>
        public static string SemesterRegisteredStudentsList {
            get {
                return ResourceManager.GetString("SemesterRegisteredStudentsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدورات التعليمية.
        /// </summary>
        public static string Semesters {
            get {
                return ResourceManager.GetString("Semesters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة الدورات التعليمية.
        /// </summary>
        public static string SemestersList {
            get {
                return ResourceManager.GetString("SemestersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنس.
        /// </summary>
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شافعي.
        /// </summary>
        public static string Shafeey {
            get {
                return ResourceManager.GetString("Shafeey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض مقابلة قبول الطالب.
        /// </summary>
        public static string ShowStudentAdmissionInterview {
            get {
                return ResourceManager.GetString("ShowStudentAdmissionInterview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أعزب.
        /// </summary>
        public static string Single {
            get {
                return ResourceManager.GetString("Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المرحلة الدراسية.
        /// </summary>
        public static string Stage {
            get {
                return ResourceManager.GetString("Stage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ البداية.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطالب.
        /// </summary>
        public static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحة غياب الطالب.
        /// </summary>
        public static string StudentAbsencePage {
            get {
                return ResourceManager.GetString("StudentAbsencePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة أولياء الأمور.
        /// </summary>
        public static string StudentGuardiansList {
            get {
                return ResourceManager.GetString("StudentGuardiansList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة الطلاب.
        /// </summary>
        public static string StudentList {
            get {
                return ResourceManager.GetString("StudentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطلاب.
        /// </summary>
        public static string StudentManagement {
            get {
                return ResourceManager.GetString("StudentManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحة بيانات الطالب.
        /// </summary>
        public static string StudentPage {
            get {
                return ResourceManager.GetString("StudentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورة الطالب.
        /// </summary>
        public static string StudentPhoto {
            get {
                return ResourceManager.GetString("StudentPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلاب.
        /// </summary>
        public static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مراحل الدراسة.
        /// </summary>
        public static string StudyStages {
            get {
                return ResourceManager.GetString("StudyStages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدرس.
        /// </summary>
        public static string Teacher {
            get {
                return ResourceManager.GetString("Teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدرسـون.
        /// </summary>
        public static string TeachersAdmin {
            get {
                return ResourceManager.GetString("TeachersAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة المدرسين.
        /// </summary>
        public static string TeachersList {
            get {
                return ResourceManager.GetString("TeachersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فترة التدريس.
        /// </summary>
        public static string TeachingPeriod {
            get {
                return ResourceManager.GetString("TeachingPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوظيفة.
        /// </summary>
        public static string TheProfession {
            get {
                return ResourceManager.GetString("TheProfession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحلقة التدريسية.
        /// </summary>
        public static string Track {
            get {
                return ResourceManager.GetString("Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض صفحة تسجيل الطالب.
        /// </summary>
        public static string ViewRegisteredStudentPage {
            get {
                return ResourceManager.GetString("ViewRegisteredStudentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أرمل.
        /// </summary>
        public static string Widow {
            get {
                return ResourceManager.GetString("Widow", resourceCulture);
            }
        }
    }
}
